### ISSUE TITLE
what would be a nice secure value for -allowfrom?

### ISSUE THREAD

**Issue by hanoii** [wollomatic/socket-proxy#2]
First off, thanks for this! I am trying out some setup and was using your suggested 0.0.0.0/8 on https://github.com/wollomatic/traefik2-hardened but it didn't work on osx, it obviously worked with `0.0.0.0/0`. Wouldn't this generally be the IP of the traefik service? If so, it might be good to pass the service name and have go resolve its ip? It should be able to resolve it, right?

**Comment by wollomatic** [comment]
Thank you, @hanoii, for reporting the bug on my traefik2-hardened repository. I have fixed it to `0.0.0.0/0`. The `/8` was a typo.

I recall considering the use of the service name, but I decided against it to keep the complexity low. But after working with socket-proxy for a while, I agree that using the service name would be very helpful. I will add it to my to-do list.

Thank you again,
Wolfgang.

**Comment by wollomatic** [comment]
As an alternative to an IP network, the `-allowfrom`-Parameter now also accepts a hostname since the pre-release of 1.1.0: `wollomatic/socket-proxy:1.1.0-beta1`.

So for example
`      - '-allowfrom=traefik'`
is valid now.

Further testing and some optimisation is still required.
