### ISSUE TITLE
[Idea] Expose the filtered UNIX socket as... a UNIX socket!

### ISSUE THREAD

**Issue by andrebrait** [wollomatic/socket-proxy#29]
**Is your feature request related to a problem? Please describe.**

Some applications simply do not like having a remote host to listen to and would much rather have a UNIX socket to connect to. Plus, UNIX socket skip the whole TCP/IP stack, routing, etc. and may thus be faster. 

Currently all socket proxies that may be used to control what and how something can access a UNIX socket expose the functionality through the network, usually plain TCP.

**Describe the solution you'd like**

Find a way to expose the filtered and controlled operations in a UNIX socket. The user should be able to set the path desired for such socket and make that available for mounting to e.g. another container (speaking specifically about Docker here).

**Describe alternatives you've considered**

None.

**Additional context**

I know some types of filtering, like allowed IPs and hosts, are impossible (and besides the point) if exposing it as a UNIX socket.

Given UNIX sockets require a system call and are a kernel feature, I'm not sure what it takes to make use of them from within a container, but hey, that's the point of opening the issue as well. I'm gonna do some investigation.

**Comment by wollomatic** [comment]
Hi Andre,

thanks for the suggestion. I also thought about this before and I think it will be implemented in a (not-so-)future release.

**Comment by wollomatic** [comment]
Hi Andre, thanks again for the suggestion.
After testing a while, it seems to work stable, so I released a new version today.

**Comment by andrebrait** [comment]
@wollomatic that's awesome 

Ps.: there's a typo in the env var name here: https://github.com/wollomatic/socket-proxy/commit/2f10b68936ef0908122af72621bc7643a33aad45#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R48

**Comment by wollomatic** [comment]
Thanks, I'll fix the typo right now

**Comment by andrebrait** [comment]
Closing this since you've implemented it.

Ps.: in case you didn't know, if you include `fixes #issueNumber` or `closes #issueNumber` in the __*commit message*__ or the PR description, GitHub automatically closes the issue when the PR gets merged or the commit gets pushed.

See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
