### ISSUE TITLE
SP_PROXYSOCKETENDPOINTFILEMODE is being ignored

### ISSUE THREAD

**Issue by justsomescripts** [wollomatic/socket-proxy#35]
**Describe the bug**
SP_PROXYSOCKETENDPOINTFILEMODE is being ignored

**To Reproduce**
1. Set `SP_PROXYSOCKETENDPOINTFILEMODE` to anything other than 0400
2. Check the logs

**Expected behavior**
File mode is set to the defined value

**Comment by wollomatic** [comment]
Thanks for reporting the bug and fixing this issue!
